# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.__version__, np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tmvlc1e1/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tmvlc1e1/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=24
    pc file directory: D:/a/numpy/numpy/.openblas
    version: 0.3.30
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tmvlc1e1/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include
    lib directory: C:/Users/runneradmin/AppData/Local/Temp/cibw-run-tmvlc1e1/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.30  US

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
a = np.random.random((2,3,5))
# other options
# np.random.randint(1, 10, size=(2, 3, 5))
# np.random.rand(2, 3, 5)


### 4. Print a.


In [4]:
print(a)

[[[0.59644369 0.68412991 0.12047784 0.45088753 0.350533  ]
  [0.68840549 0.2574251  0.02655595 0.62233128 0.9661567 ]
  [0.2540145  0.05585894 0.64985765 0.03593238 0.96263097]]

 [[0.72588471 0.69837982 0.00441082 0.18763738 0.9336067 ]
  [0.28871025 0.01111914 0.72554779 0.8862935  0.90188362]
  [0.94668774 0.95392361 0.27702295 0.18473678 0.84301565]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
b = np.ones((5, 2, 3)) 


### 6. Print b.


In [6]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
a.size == b.size


True


### 8. Are you able to add a and b? Why or why not?


In [8]:
# NO, It doesn't seem that can be added, different shape
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
c = b.transpose(1, 2, 0)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
# They have the same shape
d = a + c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [11]:
print(a)
print(d)
# They differ in the one that has been added


[[[0.59644369 0.68412991 0.12047784 0.45088753 0.350533  ]
  [0.68840549 0.2574251  0.02655595 0.62233128 0.9661567 ]
  [0.2540145  0.05585894 0.64985765 0.03593238 0.96263097]]

 [[0.72588471 0.69837982 0.00441082 0.18763738 0.9336067 ]
  [0.28871025 0.01111914 0.72554779 0.8862935  0.90188362]
  [0.94668774 0.95392361 0.27702295 0.18473678 0.84301565]]]
[[[1.59644369 1.68412991 1.12047784 1.45088753 1.350533  ]
  [1.68840549 1.2574251  1.02655595 1.62233128 1.9661567 ]
  [1.2540145  1.05585894 1.64985765 1.03593238 1.96263097]]

 [[1.72588471 1.69837982 1.00441082 1.18763738 1.9336067 ]
  [1.28871025 1.01111914 1.72554779 1.8862935  1.90188362]
  [1.94668774 1.95392361 1.27702295 1.18473678 1.84301565]]]



### 12. Multiply a and c. Assign the result to e.


In [12]:
e = a * c




### 13. Does e equal to a? Why or why not?


In [13]:
e == a
# Yes, they are equal because multiplying by 1. will result in the same value



array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [15]:
d_mean

np.float64(1.5096833805661651)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [16]:
f = np.empty((2, 3, 5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [17]:
f[(d > d_min) & (d < d_mean)] = 25
f[(d < d_max) & (d > d_mean)] = 75
f[d == d_mean] = 50
f[d == d_max] = 100
f[d == d_min] = 0





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [18]:
print(d)
print(f)

[[[1.59644369 1.68412991 1.12047784 1.45088753 1.350533  ]
  [1.68840549 1.2574251  1.02655595 1.62233128 1.9661567 ]
  [1.2540145  1.05585894 1.64985765 1.03593238 1.96263097]]

 [[1.72588471 1.69837982 1.00441082 1.18763738 1.9336067 ]
  [1.28871025 1.01111914 1.72554779 1.8862935  1.90188362]
  [1.94668774 1.95392361 1.27702295 1.18473678 1.84301565]]]
[[[ 75.  75.  25.  25.  25.]
  [ 75.  25.  25.  75. 100.]
  [ 25.  25.  75.  25.  75.]]

 [[ 75.  75.   0.  25.  75.]
  [ 25.  25.  75.  75.  75.]
  [ 75.  75.  25.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [19]:
# Convert array to strings to be able to store string values
f = f.astype(str)
f[(d > d_min) & (d < d_mean)] = 'B'
f[(d < d_max) & (d > d_mean)] = 'D'
f[d == d_mean] = 'C'
f[d == d_max] = 'E'
f[d == d_min] = 'A'
print(f)

[[['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'B' 'D' 'E']
  ['B' 'B' 'D' 'B' 'D']]

 [['D' 'D' 'A' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']
  ['D' 'D' 'B' 'B' 'D']]]
